name: basic action
on: [push]
jobs:
  one:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node_version: [6,8,10]
      fail-fast: true
      max-parallel: 2
    steps:
      - name: log node v
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: log node v2
        run:
          node -v


