name: basic action
on: [pull_request]
jobs:
  one:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node_version: [6,8,10]
        exclude:
          - os: ubuntu-latest
            node_version: 8
          - os: windows-latest
            node_version: 6
          - os: windows-latest
            node_version: 8                        
          - os: windows-latest
            node_version: 10            
      fail-fast: true
      max-parallel: 2
    steps:
      - name: log node v
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: log node v2
        run:
          node -v


