name: basic action
on: [push]
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: log node v
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: log node v2
        run:
          node -v


